### ISSUE TITLE
Transaction data fails to load

### ISSUE THREAD

**Issue by yarosz** [Rodrigolmti/lunch_money_companion#1]
![Screenshot_20240609-081123.png](https://github.com/Rodrigolmti/lunch_money_companion/assets/3142961/069a1c52-43c3-42fb-94be-fb5c28b4abe9)

**Comment by Rodrigolmti** [comment]
Thanks for reporting, this issue was fixed on version 1.5.0

**Comment by yarosz** [comment]
Awesome! Thanks for the fix.
